### ISSUE TITLE
Alright let's work out the plot

### ISSUE THREAD

**Issue by Richard5656** [AudioTore/rpg#1]
This frame work is pretty good to build off of, now we just need the plot.

**Comment by AudioTore** [comment]
How about hmm.. Maybe a dungeon fighting game

**Comment by AudioTore** [comment]
But the thing is i want the game to be able to move around characters using wasd keys.

**Comment by Richard5656** [comment]
I see

**Comment by Richard5656** [comment]
This game will run very fast because it is mostly in ASCII

**Comment by Richard5656** [comment]
We will need to program a few maps maybe we can layer the dungeons in floors.

**Comment by Richard5656** [comment]
Ok what part would you like to start with?

**Comment by AudioTore** [comment]
First part

**Comment by AudioTore** [comment]
Or actually i should say maybe we should start out by making a character system. Like inventory and character looks. However character looks don't matter since its in ascii

**Comment by Richard5656** [comment]
Why don't we combine multiplayer with the story mode?

**Comment by Richard5656** [comment]
Ok

**Comment by Richard5656** [comment]
Where are we going to host the server?

**Comment by AudioTore** [comment]
@Richard5656 I don't know don't worry about that know. Lets try and code the character stats and coding them to move around

**Comment by Richard5656** [comment]
Ok

**Comment by Richard5656** [comment]
I'm kinda scared since you can't handle 2D arrays yet.

**Comment by AudioTore** [comment]
@Richard5656 Lol We will figure it out

**Comment by AudioTore** [comment]
That's what a project does. It expands knowledge during the making of it.

**Comment by Richard5656** [comment]
I already know how to make the entire thing from the server to the map to the stats. I'm just not sure what you want me to do.

**Comment by Richard5656** [comment]
You can literally ask me to do anything for the project.

**Comment by AudioTore** [comment]
@Richard5656 Maybe make some characters with a working inventory?

**Comment by Richard5656** [comment]
Do you want me to use classes?

**Comment by AudioTore** [comment]
Sure! Whatever it takes.

**Comment by Richard5656** [comment]
Ok

**Comment by AudioTore** [comment]
They don't need to look good

**Comment by Richard5656** [comment]
Ok

**Comment by Richard5656** [comment]
So we should program the intro first.

**Comment by Richard5656** [comment]
I'm not currently next to my laptop so I'll get back to you later with the code.

**Comment by Richard5656** [comment]
Just list the stats, characters, and some items first and I'll see what I can put together.

**Comment by AudioTore** [comment]
Alright

**Comment by AudioTore** [comment]
Have about for stats we can have: gold for purchasing stuff, health, then for items: swords and pickaxes

**Comment by Richard5656** [comment]
Ok I'll use some python to put that together

**Comment by Richard5656** [comment]
So will we be able to create custom characters. Do the items have durability?

**Comment by AudioTore** [comment]
@Richard5656 For simplicity no

**Comment by Richard5656** [comment]
Ok

**Comment by Richard5656** [comment]
Here are the classes.


Class character:
    inventory = []
    def __init__(self,hp,level,gender):
        self.hp = hp
        self.level = level
        self.gender =""
class item:
    name = ""

**Comment by Richard5656** [comment]
class character:
    inventory = []
    def __init__(self,hp,level,gender):
        self.hp = hp
        self.level = level
        self.gender =""
class item:
    name = ""

**Comment by Richard5656** [comment]
I'll leave the classes in a pull request.

**Comment by AudioTore** [comment]
Alright!

**Comment by Richard5656** [comment]
Should I build a tier system like Minecrafts wood through netherite?

**Comment by Richard5656** [comment]
So currently I've built a small game engine that we can use to generate enemies and characters. I'm planning to program in a map generator too to make it easier for the maps. All you need to do is to utilize the functions I have put inside to make a game. I'll explain the functions once I finish programming everything in.

**Comment by AudioTore** [comment]
@Richard5656 Dang really!? Alright!

**Comment by Richard5656** [comment]
Yeah thats why I programed the engine to make things go a little faster when programing the game.

**Comment by Richard5656** [comment]
I saw the new video and thanks for the shout out. But you're underestimating the terminal https://www.youtube.com/watch?v=94YOd0gimF8. Anyways so yeah I finished the game engine. Im just writing the tutorial for it. I have a question about the maps. Im currently using seed generation for the maps. Are you ok with that?

**Comment by Richard5656** [comment]
Ok i have submitted them at
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-3
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-2

All you need to do is let the changes go through.
Also do not allow https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-1 
because it was the worse version of https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-2.

**Comment by AudioTore** [comment]
@Richard5656 im ok with seeds

**Comment by Richard5656** [comment]
Oh thank's that really speeds up the world building.

**Comment by Richard5656** [comment]
So have you checked out the code yet?

**Comment by AudioTore** [comment]
@Richard5656 Sorry im a little bit busy i will later.

**Comment by Richard5656** [comment]
Ok. It sounds like we are creating rouge. https://en.m.wikipedia.org/wiki/Rogue_(video_game)

**Comment by AudioTore** [comment]
@Richard5656 Something like that. But with shops and multiplayer. And maybe even a story like missions. But anyways im back so where's the code?

**Comment by Richard5656** [comment]
> Ok i have submitted them at [main...Richard5656:patch-3](https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-3) [main...Richard5656:patch-2](https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-2)
> 
> All you need to do is let the changes go through. Also do not allow [main...Richard5656:patch-1](https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-1) because it was the worse version of [main...Richard5656:patch-2](https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-2).

Here

**Comment by AudioTore** [comment]
@Richard5656 Thanks!

**Comment by AudioTore** [comment]
@Richard5656 i merged it!

**Comment by Richard5656** [comment]
Cool

**Comment by AudioTore** [comment]
@Richard5656 So i made a few maps for testing ima upload them. Then do a @ symbol for a character and place it on the map for testing.

**Comment by Richard5656** [comment]
ok

**Comment by Richard5656** [comment]
So do you want me to use your map to generate maps?

**Comment by AudioTore** [comment]
@Richard5656 No. I made a map for people to spawn at. People will spawn at the town that's full of shop's and people requesting missions.

**Comment by AudioTore** [comment]
I added a play.py file in the data folder containing some maps

**Comment by Richard5656** [comment]
Oh I see

**Comment by Richard5656** [comment]
Can you give me an example of a dungeon map?

**Comment by Richard5656** [comment]
I'm just not sure what I'm supposed to generate.

**Comment by AudioTore** [comment]
@Richard5656 For now try and see if you can find a way to put a character on the map and make it move.

**Comment by Richard5656** [comment]
Oh that's easy.

**Comment by Richard5656** [comment]
But the combat will have to be turn based because to make this game cross platform I must not use live wasd.

**Comment by Richard5656** [comment]
It's probably not ideal for the player to move through the town with wasd because of the console. Is it ok if we list it like this?

[1] shop
[2] missions board

**Comment by Richard5656** [comment]
I have finished creating movement. But I need to work on the collision.

**Comment by Richard5656** [comment]
its all done

**Comment by AudioTore** [comment]
@Richard5656 Sure!

**Comment by Richard5656** [comment]
let me just give you the code

**Comment by Richard5656** [comment]
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-4?expand=1
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-5?expand=1

**Comment by Richard5656** [comment]
I had to update the game engine to get it to work

**Comment by Richard5656** [comment]
Now ill need to parse your maps to be able to use movement on them.

**Comment by Richard5656** [comment]
Im open for critisism on the movement.

**Comment by Richard5656** [comment]
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-6
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-7

Movement for the large town map with the quests board and the shop code.

**Comment by Richard5656** [comment]
Now that that's finished we need to focus on the introduction like the intro to the game.

**Comment by AudioTore** [comment]
@Richard5656 I will do it. After a hour tho i have some stuff to do first.

**Comment by AudioTore** [comment]
I moved the game engine and stuff into the data folder

**Comment by Richard5656** [comment]
Ok

**Comment by Richard5656** [comment]
Do you have any ideas for the final boss?

**Comment by AudioTore** [comment]
Well first lets test it out. Are we ready to test out the character movement?

**Comment by Richard5656** [comment]
Oh I've already tested it

**Comment by Richard5656** [comment]
There's 1 bug but it can be fixed easily.

**Comment by AudioTore** [comment]
ModuleNotFoundError: No module named 'town_map'

**Comment by Richard5656** [comment]
Ok the filenames have to match with the modules

**Comment by AudioTore** [comment]
there is no town_map

**Comment by Richard5656** [comment]
what?

**Comment by Richard5656** [comment]
what happened?

**Comment by Richard5656** [comment]
oh wait I found it
you didnt add this patch
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-7

**Comment by Richard5656** [comment]
so how do you like the movement?

**Comment by AudioTore** [comment]
so do i run town_map.py to run the test?

**Comment by Richard5656** [comment]
No run the movement_test_town.py to check out the town map with movement.

**Comment by Richard5656** [comment]
Did you figure bout the movement?

**Comment by AudioTore** [comment]
ModuleNotFoundError: No module named 'town_ma

**Comment by Richard5656** [comment]
Town_map

**Comment by Richard5656** [comment]
Move town_map.py into data

**Comment by AudioTore** [comment]
Im in the file it works. But do you move exactly?

**Comment by AudioTore** [comment]
oh nvm it works!

**Comment by Richard5656** [comment]
Is it ok?

**Comment by AudioTore** [comment]
yeah its fine

**Comment by Richard5656** [comment]
Ok

**Comment by Richard5656** [comment]
So about the story?

**Comment by Richard5656** [comment]
I was thinking that we could create like some final goal the character could do.

**Comment by Richard5656** [comment]
I'm going to suggest an idea for the story. What if we have to defeat a tyrant who has some ultimate power and the only way to defeat this power is to obtain an artifact or ability from the dungeons and we start with 50 floors of dungeon and we have 5 bosses.

**Comment by Richard5656** [comment]
I've just programed in the menu for the shop and the player menu. I'm just going to start adding items that can be bought and sold. Also I'm going to add the dungeon feature.

**Comment by AudioTore** [comment]
@Richard5656 Woah! slow down i don't want you to be doing all the work!

**Comment by AudioTore** [comment]
However im gonna need the game engine explained to be.

**Comment by AudioTore** [comment]
Mostly the character movement

**Comment by Richard5656** [comment]
Ok ill explain the character movement

**Comment by Richard5656** [comment]
Are you in middle school, or high school? Depening on which I can use certain math from either one to to explain to you how the character movement works.

**Comment by Richard5656** [comment]
If you are at least familiar with grid graphs this should be easy.

**Comment by Richard5656** [comment]
Don't worry Im only doing 5% of the work right now it's just the setup.

**Comment by Richard5656** [comment]
The shop has been automated. The pickaxe works now too.

**Comment by Richard5656** [comment]
Anyways I'm going to leave it at here and explain to you the mechanics of the movement and the game engine.

**Comment by Richard5656** [comment]
Im actually emulating a graph in python. This is a teqnique used in 2d games where you can emulate a graph and create movement with it. Heres a demonstration.
Move the x and y sliders left and right on this desmos. 
You will notice the Dot move up and down , left or right in accordance to the sliders.

The x slider handles left or right.
The y slider handles up and down. 

That's basicly what we are doing.

https://www.desmos.com/calculator/bq8anja80g

**Comment by Richard5656** [comment]
:P I may have complicated things slightly to make it easier to use the map generation algorithm with a little multiplication... But yeah this is basicly how it works.

**Comment by Richard5656** [comment]
Practically all the algorithms I've programed in don't include anything too complicated its just random numbers with seeds or just grids for displaying text. 😎 Im just a beginneer too.

**Comment by Richard5656** [comment]
Well now Ill explain the rest of the game engine. Basicly im using a paradigm(way) called object oriented programing.

If you read through this then you'll understand the code for the game engine. 
https://www.w3schools.com/python/python_classes.asp

**Comment by AudioTore** [comment]
Anyway to subtract gold when player buys something?

**Comment by Richard5656** [comment]
I already worked that out I just subtract the gold using gold -= price a.k.a gold = gold - price.

**Comment by Richard5656** [comment]
Should I upload my progress on the game to catch you up?

**Comment by Richard5656** [comment]
I was wondering if you could connect you're start menu code to my filler story code. I created a minature story to go with the game as a place holder for any story you might have. Its only a place holder until we can work that out.

**Comment by AudioTore** [comment]
@Richard5656 Sure

**Comment by Richard5656** [comment]
Ok ill upload my current code and you can have a look at it. BTW the load game on the first screen doesn't actually load the game it crashes because I havent added that feature yet.

**Comment by Richard5656** [comment]
I have uploaded the new files they should be at 
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-9
https://github.com/AudioTore/Rthon/compare/main...Richard5656:patch-8

**Comment by Richard5656** [comment]
I commented the game engine so if you have any questions you can ask me.

**Comment by Richard5656** [comment]
Do you have a little understanding of the movement yet?

**Comment by AudioTore** [comment]
Much more human readably

**Comment by Richard5656** [comment]
Oh thank you. Sorry I was speed running creating the game engine.

**Comment by Richard5656** [comment]
So do we TP to the dungeons from the menu or would you like to add a map that did that for us?

**Comment by Richard5656** [comment]
Actually we are paractically done with the frame work all we have to do is divide the work.

**Comment by Richard5656** [comment]
Dev log 1: 
Im going to start doing devlogs.

Just finished implementing the dungeons into the game all I need to do now is to add hit detection.

**Comment by AudioTore** [comment]
@Richard5656 Is there anyway to subtract gold when buying something using variables perhaps?

**Comment by Richard5656** [comment]
We are currently using variables for subtraction.

**Comment by Richard5656** [comment]
Could you mean with out the player.gold?

**Comment by AudioTore** [comment]
@Richard5656 Yeah

**Comment by Richard5656** [comment]
We could do that.

**Comment by Richard5656** [comment]
Would you like to refactor the code to do that?

**Comment by AudioTore** [comment]
@Richard5656 Yeah .

**Comment by Richard5656** [comment]
Ok.

**Comment by Richard5656** [comment]
@AudioTore Ok

**Comment by Richard5656** [comment]
@AudioTore I'm actually going to need you to handle the PvE.

**Comment by Richard5656** [comment]
The PvE is about medium difficulty. So that should be perfect.

**Comment by Richard5656** [comment]
Developer entry 2
Dungeons added
Pickaxe works in all directions now.

**Comment by Richard5656** [comment]
@AudioTore 😐 Now the frameworks completely done I'm going to search for bugs. To give you a chance to catch up on the game engine.

**Comment by Richard5656** [comment]
Don't feel shy to ask questions about the game engine. Frankly I don't understand some of the stuff I used for it.

**Comment by AudioTore** [comment]
@Richard5656 I honestly don't understand the code of the game engine

**Comment by Richard5656** [comment]
Actually I was planning to rewrite some parts of it in C or C++ because it ran too slow. But we can take it step by step.

**Comment by AudioTore** [comment]
No just keep it in python.

**Comment by Richard5656** [comment]
You sure. We can use C or C++ extension modules in python?

**Comment by AudioTore** [comment]
@Richard5656 i just renamed just to rpg and made a more simplier version of Rthon that i can understand.

**Comment by Richard5656** [comment]
Oh cool

**Comment by AudioTore** [comment]
@Richard5656 Im sorry :(

**Comment by AudioTore** [comment]
@Richard5656  i just had too i felt unorganized with the code that was being written

**Comment by Richard5656** [comment]
@AudioTore Yeah my code is unorginized

**Comment by Richard5656** [comment]
@AudioTore it's ok. I understand that my code is messy.

**Comment by Richard5656** [comment]
@AudioTore I'm going to be honest with you I didn't expect you to make WASD to a ASCII game. Are we still going to use WASD?

**Comment by AudioTore** [comment]
@Richard5656 Yeah but as simple as possible. It has to be code that i understand.

**Comment by Richard5656** [comment]
Are you familiar with python lists?

**Comment by AudioTore** [comment]
@Richard5656 Yeah

**Comment by AudioTore** [comment]
Like 2d lists?

**Comment by AudioTore** [comment]
oh just lists Yeah

**Comment by Richard5656** [comment]
Oh thank you. I'll write it like that.

**Comment by AudioTore** [comment]
@Richard5656 Alright

**Comment by Richard5656** [comment]
That should be understandable enough. 😔 Sorry the previous game engine used a 1d list which I used a formula to convert into a 2d list.

**Comment by Richard5656** [comment]
Sorry if that was to complex.

**Comment by Richard5656** [comment]
So no more classes?

**Comment by AudioTore** [comment]
@Richard5656 Is it possible to make movement without classes?

**Comment by Richard5656** [comment]
It's possible but classes made it easier to keep track of what was moving.

**Comment by Richard5656** [comment]
Now that I think of it the code would work slightly faster without classes.

**Comment by Richard5656** [comment]
@AudioTore It's your call.

**Comment by AudioTore** [comment]
@Richard5656 Without classes

**Comment by Richard5656** [comment]
@AudioTore Ok.

**Comment by Richard5656** [comment]
So are you posting the code?

**Comment by AudioTore** [comment]
I did its in the rthon repository. This repository is just rpg

**Comment by Richard5656** [comment]
Oh ok

**Comment by Richard5656** [comment]
I see it now. Should I start an issues there?

**Comment by AudioTore** [comment]
@Richard5656 Sure!
